"""Compile an algorithm into a causalab CausalModel and run interventions on it.

Every layer a value is carried through becomes a relay node (``P__L6 = V(P)``)
and every reader reads the node one layer below itself, so an interchange
intervention on cell (l, t) is an ordinary causalab intervention on the nodes
at layer l. Only variables with the same name are swapped (design doc Q9).
"""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import json
import re
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from causalab.causal import CausalModel

from algorithm_hypothesis.placement import birth, nodes_at, readers, span_end
from algorithm_hypothesis.primitives import PRIMITIVES
from algorithm_hypothesis.runtime import FunctionError, strip_function
from algorithm_hypothesis.schema import EMB, Algorithm, Ref, Variable, problems
from algorithm_hypothesis.values import key_of, show


class AlgorithmError(ValueError):
    """The algorithm can't be compiled; the message lists every problem."""


# ------------------------------------------------------------------ codegen


def _node(alg: Algorithm, key: str, layer: int) -> str:
    """causalab node name of value `key` as it sits at `layer`."""
    if key.startswith("t:"):
        t = int(key[2:])
        return f"tok[{t}]" if layer == EMB else f"tok{t}__L{layer}"
    v = alg.by_id()[key[2:]]
    return v.name if layer == v.layer else f"{v.name}__L{layer}"


def _read(alg: Algorithm, ref: Ref, reader_layer: int) -> str:
    """Expression a variable at `reader_layer` uses to read `ref`."""
    at = reader_layer - 1
    if ref.variable is None:
        return f"_p.as_token({_node(alg, ref.key, at)}, {ref.token})"
    return _node(alg, ref.key, at)


def _python_fn_name(v: Variable) -> str:
    return f"_fn_{v.name}"


def _python_function(v: Variable) -> tuple[str, list[str]]:
    """A custom Python function as module-level source named ``_fn_<name>``,
    and its parameter names. Stripped the same way as in the browser
    (runtime.strip_function), so it behaves the same in both."""
    try:
        tree, params = strip_function(v.function.source or "", _python_fn_name(v))
    except FunctionError as exc:
        raise AlgorithmError(f"{v.name}: {exc}") from exc
    return ast.unparse(tree), params


def _call(alg: Algorithm, v: Variable, params: dict[str, list[str]]) -> str:
    def arg_expr(arg, many: bool) -> str:
        items = [_read(alg, r, v.layer) for r in arg.refs]
        if many or len(items) != 1:
            return "[" + ", ".join(items) + "]"
        return items[0]

    if v.function.kind == "python":
        parts = [f"{a.name}={arg_expr(a, False)}" for a in v.args]
        if "template" in params.get(v.id, []):
            parts.append("template=TEMPLATE")
        return f"{_python_fn_name(v)}({', '.join(parts)})"

    prim = PRIMITIVES[v.function.name]
    by_name = {a.name: a for a in v.args}
    parts = [f"{s.name}={arg_expr(by_name[s.name], s.many)}" for s in prim.slots]
    for o in prim.options:
        value = v.function.options.get(o.name, o.default)
        if isinstance(o.default, float):
            value = float(value)
        parts.append(f"{o.name}={value!r}")
    return f"_p.{prim.name}({', '.join(parts)})"


def generate_source(alg: Algorithm, template_tokens: list[str]) -> str:
    """Python source of a module defining ``algorithm``, a causalab @mechanism."""
    n = len(template_tokens)
    issues = problems(alg, n)
    if issues:
        raise AlgorithmError("\n".join(issues))
    rd = readers(alg)
    lines = [
        f"# Generated by algorithm_hypothesis from {alg.name!r}. Do not edit by hand.",
        "import math  # noqa: F401  (available to custom Python functions)",
        "from causalab.causal import Dom, FamilyDom, V, mechanism",
        "from algorithm_hypothesis import primitives as _p",
        "from algorithm_hypothesis.values import Distribution, Pair, Token, show  # noqa: F401",
        "",
        "ANY = Dom(object)",
        f"TEMPLATE = {tuple(template_tokens)!r}",
    ]
    params: dict[str, list[str]] = {}
    for v in alg.variables:
        if v.function.kind == "python":
            src, params[v.id] = _python_function(v)
            lines += ["", "", src]
    lines += ["", "", "@mechanism", f"def algorithm(tok: FamilyDom(Dom(str), size={n})):"]

    token_keys = sorted((k for k in rd if k.startswith("t:")), key=lambda k: int(k[2:]))
    for layer in range(alg.grid.layers):
        block: list[str] = []
        for key in token_keys:
            if layer <= span_end(alg, key, rd):
                block.append(f"    {_node(alg, key, layer)} = V({_node(alg, key, layer - 1)}, domain=ANY)")
        for v in alg.variables:
            key = f"v:{v.id}"
            if v.layer < layer <= span_end(alg, key, rd):
                block.append(f"    {_node(alg, key, layer)} = V({_node(alg, key, layer - 1)}, domain=ANY)")
        for v in sorted((v for v in alg.variables if v.layer == layer), key=lambda v: v.token):
            block.append(f"    {v.name} = V({_call(alg, v, params)}, domain=ANY)  # token {v.token}")
        if block:
            lines.append(f"    # L{layer}")
            lines += block
    out = alg.by_id()[alg.output]
    lines += [
        "    raw_input = V(_p.render(tok), domain=Dom(str))  # noqa: F841",
        f"    raw_output = V(_p.display({out.name}), domain=Dom(str))  # noqa: F841",
        f"    return {out.name}",
        "",
    ]
    return "\n".join(lines)


def _load_module(source: str):
    digest = hashlib.sha256(source.encode()).hexdigest()[:16]
    name = f"_algorithm_hypothesis_{digest}"
    if name in sys.modules:
        return sys.modules[name]
    path = Path(tempfile.gettempdir()) / "algorithm_hypothesis" / f"{name}.py"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(source)
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


# ------------------------------------------------------------- interventions


@dataclass
class InterventionResult:
    """An interchange intervention from a source cell into a target cell."""

    ok: bool
    reason: str | None
    swapped: list[str]  # node keys whose source values were swapped in
    target: Any  # CausalTrace of the target input (shared; copy before modifying)
    counterfactual: Any | None  # CausalTrace after the intervention
    output: Any  # counterfactual output, or the target's output if not ok
    empty: bool = False  # nothing lives in one of the cells


@dataclass
class SweepRow:
    layer: int
    output: Any
    status: str  # "ok" | "empty" | "unpaired"


class CompiledAlgorithm:
    """An algorithm compiled to causalab, ready to run and intervene on."""

    def __init__(self, alg: Algorithm, template_tokens: list[str]):
        self.algorithm = alg
        self.template_tokens = list(template_tokens)
        self.source = generate_source(alg, self.template_tokens)
        module = _load_module(self.source)
        placement = {v.name: (v.token, v.layer) for v in alg.variables}
        self.model = CausalModel(module.algorithm, id=re.sub(r"\W+", "_", alg.name).lower(), print_pos=placement)
        self.output_name = alg.by_id()[alg.output].name
        self._runs: dict[tuple[str, ...], Any] = {}

    @property
    def n_tokens(self) -> int:
        return len(self.template_tokens)

    def run(self, tokens: list[str]):
        """A fresh trace of the algorithm on `tokens` (safe to modify)."""
        return self._run(tokens).copy()

    def _run(self, tokens: list[str]):
        # Cached and shared: callers inside this class only read it or copy it.
        key = tuple(tokens)
        if key not in self._runs:
            if len(key) != self.n_tokens:
                raise ValueError(f"Expected {self.n_tokens} tokens (the template's), got {len(key)}.")
            self._runs[key] = self.model.new_trace({"tok": list(key)})
        return self._runs[key]

    def output(self, trace) -> Any:
        return trace[self.output_name]

    def value_at(self, trace, key: str, layer: int) -> Any:
        return trace[_node(self.algorithm, key, layer)]

    def interchange_intervention(
        self,
        source_tokens: list[str],
        target_tokens: list[str],
        source_cell: tuple[int, int],
        target_cell: tuple[int, int],
    ) -> InterventionResult:
        """Swap the values in `source_cell` of the source run into
        `target_cell` of the target run. Cells are (layer, token)."""
        alg = self.algorithm
        target = self._run(target_tokens)
        s_nodes = nodes_at(alg, *source_cell)
        t_nodes = nodes_at(alg, *target_cell)
        if not s_nodes or not t_nodes:
            which = "source" if not s_nodes else "target"
            return InterventionResult(False, f"Nothing lives in that {which} cell.", [], target, None, self.output(target), empty=True)
        shared = [k for k in t_nodes if k in s_nodes]
        if not shared:
            return InterventionResult(
                False,
                "The two cells share no variables. Interventions only swap variables with the same name.",
                [],
                target,
                None,
                self.output(target),
            )
        source = self._run(source_tokens)
        values = {_node(alg, k, target_cell[0]): source[_node(alg, k, source_cell[0])] for k in shared}
        counterfactual = target.copy()
        counterfactual.intervene_many(values)
        return InterventionResult(True, None, shared, target, counterfactual, self.output(counterfactual))

    def token_sweep(self, source_tokens, target_tokens, source_token: int, target_token: int) -> list[SweepRow]:
        """Intervene on one token at every layer, embedding row included."""
        rows = []
        for layer in range(EMB, self.algorithm.grid.layers):
            r = self.interchange_intervention(source_tokens, target_tokens, (layer, source_token), (layer, target_token))
            status = "ok" if r.ok else ("empty" if r.empty else "unpaired")
            rows.append(SweepRow(layer, r.output, status))
        return rows

    def full_sweep(self, source_tokens, target_tokens) -> list[list[SweepRow]]:
        """token_sweep for every token into the same position."""
        return [self.token_sweep(source_tokens, target_tokens, t, t) for t in range(self.n_tokens)]


def compile_algorithm(alg: Algorithm | dict | str | Path, template_tokens: list[str] | None = None) -> CompiledAlgorithm:
    """Compile an Algorithm (or its JSON dict / file path).

    `template_tokens` defaults to the abstract tokenization of the template;
    pass the model tokenizer's tokens for model grids.
    """
    from algorithm_hypothesis.placement import tokenize_abstract

    if isinstance(alg, (str, Path)):
        alg = json.loads(Path(alg).read_text())
    if isinstance(alg, dict):
        alg = Algorithm.from_dict(alg)
    if template_tokens is None:
        template_tokens = tokenize_abstract(alg.template)
    return CompiledAlgorithm(alg, template_tokens)


__all__ = [
    "AlgorithmError",
    "CompiledAlgorithm",
    "InterventionResult",
    "SweepRow",
    "compile_algorithm",
    "generate_source",
    "birth",
    "key_of",
    "show",
]
